---
# tasks file for zabbix-agent

# echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list

- name: Add ubuntu repository for libssl1.1
  ansible.builtin.apt_repository:
    repo: deb http://security.ubuntu.com/ubuntu focal-security main

- name: Deliver zabbix-agent installation file
  ansible.builtin.copy:
    src: 'zabbix-release_6.4-1+ubuntu20.04_all.deb'
    dest: /tmp/

- name: Install Zabbix 6.2 Debian repo .deb
  ansible.builtin.apt:
    deb: /tmp/zabbix-release_6.4-1+ubuntu20.04_all.deb
    state: present
    # update_cache: yes

- name: Uninstall Zabbix Agent
  ansible.builtin.apt:
    name: zabbix-agent
    state: absent

- name: Install Zabbix Agent 2
  ansible.builtin.apt:
    name: zabbix-agent2
    state: present
    update_cache: yes

- name: Deliver zabbix_agent2.conf from template folder
  ansible.builtin.template:
    src: zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'

- name: Add zabbix-server name to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: 'ag-zbx-01'
    line: 134.0.119.213  ag-zbx-01
    # owner: root
    # group: root
    # mode: '0644'

- name: Restart zabbix-agent2
  ansible.builtin.systemd:
    state: restarted
    name: zabbix-agent2
    enabled: yes
